### ISSUE TITLE
Documentation and Support links UI is not correct.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/subscriptions-for-woocommerce#123]
WordPress version: 5.8
WooCommerce version: 5.6
Area Path: Admin panel --> MakeWebBetter --> Subscriptions For WooCommerce
Version: 1.0.3
Description: Documentation and Support links UI is not correct.
![Screenshot (73)](https://user-images.githubusercontent.com/76723329/131072414-91fc5e95-35f9-4b2b-8ac7-79b92d5214ba.png)

**Comment by muskaan-ui** [comment]
fixed

**Comment by indresh-cedcoss** [comment]
![image](https://user-images.githubusercontent.com/48907421/133100784-e04a3cf6-660d-4799-acc6-b5a74303e905.png)

should be like this
![image](https://user-images.githubusercontent.com/48907421/133100865-c5259654-75a2-4cbf-9a26-4687bd5784a0.png)

**Comment by muskaan-ui** [comment]
fixed

**Comment by muskaan-ui** [comment]
![screenshot-subscription-for-woocommerce local-2021 09 14-10_55_18](https://user-images.githubusercontent.com/68998280/133222146-32f1c0c6-1c4a-4b38-a428-c831d9a6a98e.png)

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
