### ISSUE TITLE
In subscription table pro details are available and are working.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/subscriptions-for-woocommerce#124]
WordPress version: 5.8
WooCommerce version: 5.6
Area Path: Admin panel --> MakeWebBetter --> Subscriptions For WooCommerce -> Subscription Table
Version: 1.0.3
Description: In the subscription table, pro details are available and are working. As of now after deactivating the pro plugin pro orders are available and recurring payment is getting done.
![Screenshot (74)](https://user-images.githubusercontent.com/76723329/131073138-3b645eba-4374-4e62-8b9a-7e789960aed6.png)

**Comment by indresh-cedcoss** [comment]
not an issues

**Comment by sumitshukla-cedcoss** [comment]
@ChiragGupta-CEDCOSS enhancement done

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
