### ISSUE TITLE
Subscription product order settings are not working fine.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/subscriptions-for-woocommerce#125]
WordPress version: 5.8
WooCommerce version: 5.6
Area Path: Admin panel --> MakeWebBetter --> Subscriptions For WooCommerce -> Subscription Table
Version: 1.0.3
Description: Subscription product order settings are not working fine, with a free trial recurring payment is not coming fine and without a free trial Next payment is similar to the Expiry date.
![Screenshot (75)](https://user-images.githubusercontent.com/76723329/131080795-e8988640-566e-495b-b955-fbf7b3b1e142.png)
![Screenshot (76)](https://user-images.githubusercontent.com/76723329/131080991-55b573f1-457f-448b-b4e9-fc8b151cb404.png)
![Screenshot (77)](https://user-images.githubusercontent.com/76723329/131081009-66897f05-4c8a-4d8a-a67e-ad2fb912fa39.png)

**Comment by indresh-cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Still left.
![Uploading Screenshot (50).png…]()

**Comment by indresh-cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine. But, Other issue is coming again.
![Screenshot - 2021-09-14T181437 663](https://user-images.githubusercontent.com/76723329/133259853-75b72347-cb62-4062-a2c5-a8ae05f3d6d6.png)

**Comment by sumitshukla-cedcoss** [comment]
@ChiragGupta-CEDCOSS enhancement done

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
