### ISSUE TITLE
Price rule is not getting implemented.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/subscriptions-for-woocommerce#128]
WordPress version: 5.8
WooCommerce version: 5.6
Area Path: Store-end-> Checkout
Version: 1.1.0
Description: Price rule is not getting implemented on a subscription product correctly.
![Screenshot (97)](https://user-images.githubusercontent.com/76723329/131679465-2d010385-0aba-4873-8043-27f851a94661.png)
![Screenshot (98)](https://user-images.githubusercontent.com/76723329/131679495-61a5d948-17c3-49b9-8bf7-f699d527dfba.png)

**Comment by indresh-cedcoss** [comment]
done

**Comment by ChiragGupta-CEDCOSS** [comment]
Now discount is neither displaying nor implementing. For simple and Variable products.

**Comment by indresh-cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
