### ISSUE TITLE
Welcome form is not coming fine.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/subscriptions-for-woocommerce#131]
WordPress version: 5.8
WooCommerce version: 5.6
Area Path: Admin panel-> MakeWebBetter-> Subscriptions For WoCommerce
Version: 1.1.0
Description: Welcome form is not coming fine.
-> Plugin name is not correct
![Screenshot (42)](https://user-images.githubusercontent.com/76723329/132498276-eab73816-e763-4119-accb-013962216a5d.png)

-> Skip now button can be added for better usability.
->if the plugin was already in use existing button names are not coming in welcome form
->Check this box to enable the subscription checkbox input is not getting saved if unchecked.
![Screenshot (48)](https://user-images.githubusercontent.com/76723329/132504348-9584018a-f612-43d5-8eef-996a693956cd.png)
![Screenshot (49)](https://user-images.githubusercontent.com/76723329/132504598-fc3be1ac-5204-4acb-b1fa-eb1117c17241.png)

**Comment by indresh-cedcoss** [comment]
Fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
