### ISSUE TITLE
Error & Success messages are not clearly visible for Subscription

### ISSUE THREAD

**Issue by indresh-cedcoss** [Makewebbetter/subscriptions-for-woocommerce#133]
![image](https://user-images.githubusercontent.com/48907421/133102396-ff4f3324-bf38-43f3-ae4c-331ad8196c5e.png)

https://www.loom.com/share/98e9de40d95d4c6081ec8ef6002880bb

**Comment by muskaan-ui** [comment]
fixed

**Comment by muskaan-ui** [comment]
![screenshot-subscription-for-woocommerce local-2021 09 14-10_48_46](https://user-images.githubusercontent.com/68998280/133222043-0038e5a4-7448-4371-ba38-44f8fad6a4e4.png)

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
