### ISSUE TITLE
Sign up fee is not coming fine at shop.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/subscriptions-for-woocommerce#136]
WordPress version: 5.8.1
WooCommerce version: 5.6.0
Plugin Compatibility: MWB Multi Currency Switcher For WooCommerce
Area Path: Shop
Version: 1.1.0
Description: Sign up fee is not coming fine at the shop for subscription products
![Screenshot(3)](https://user-images.githubusercontent.com/76723329/133381671-6892b62d-f452-403e-8b4c-355eb54e0c08.png)
.

**Comment by indresh-cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
