### ISSUE TITLE
Tracking setting should be updated.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/subscriptions-for-woocommerce#154]
WordPress version: 5.8.1
WooCommerce version: 5.8
Area Path: Admin panel --> MakeWebBetter --> Subscriptions For WooCommerce -> Developer
Version: 1.1.1
Description: Tracking setting should be updated.
![Screenshot](https://user-images.githubusercontent.com/76723329/140723901-a506d365-057b-47a6-8ed7-a3186a857d41.png)
![Screenshot (1)](https://user-images.githubusercontent.com/76723329/140723918-ea644fd9-fa1c-42c3-9ad2-a215b7ea3593.png)

**Comment by sumitshukla-cedcoss** [comment]
@ChiragGupta-CEDCOSS  done
