### ISSUE TITLE
Replace the link.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [Makewebbetter/subscriptions-for-woocommerce#162]
**Bug Name -** Replace the link.
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 6.1.1
**WordPress Version -** 5.9
**Plugin Version -** 
**Description -**

![image](https://user-images.githubusercontent.com/76723393/151489190-e364fbda-462a-415f-b9b0-18b1322ca71e.png)

**Comment by Shivamddeveloper** [comment]
this is issue is not showing in my site

**Comment by AnuraktSachan-CEDCOSS** [comment]
okay
