### ISSUE TITLE
Products single page description content UI

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/subscriptions-for-woocommerce#29]
WordPress version: 5.7
WooCommerce version: 5.1.0
Area Path: Store-end --> Shop --> Subscription product single page
Version: 1.0.0
Description: The Product single page description content UI is not fine, the content display should be improved according to the different content like- Product subscription price, Product signup fee, Product free trial in different lines.
Browsers: Chrome/ Firefox/ Opera
![Screenshot30](https://user-images.githubusercontent.com/76723329/111583287-2c44d800-87e2-11eb-8768-2615f7c973f9.png)

**Comment by indresh-cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
