### ISSUE TITLE
QA issues

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/subscriptions-for-woocommerce#53]
Plugin: Subscriptions For WooCommerce

QA issues Refer to attached files:
[Subscriptions For WooCommerce QA issues.docx](https://github.com/Makewebbetter/subscriptions-for-woocommerce/files/6186877/Subscriptions.For.WooCommerce.QA.issues.docx)
[subscriptions-for-woocommerce-xml.docx](https://github.com/Makewebbetter/subscriptions-for-woocommerce/files/6183175/subscriptions-for-woocommerce-xml.docx)

**Comment by indresh-cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Still left-
phpcs issues:
[subscriptions-for-woocommerce.txt](https://github.com/Makewebbetter/subscriptions-for-woocommerce/files/7218794/subscriptions-for-woocommerce.txt)

QA issue:
[subscriptions-for-woocommerce QA issues.txt](https://github.com/Makewebbetter/subscriptions-for-woocommerce/files/7218795/subscriptions-for-woocommerce.QA.issues.txt)

**Comment by indresh-cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.

**Comment by ChiragGupta-CEDCOSS** [comment]
Plugin: Subscriptions For WooCommerce
Version: 1.2.0

phpcs issues:
[subscriptions-for-woocommerce.txt](https://github.com/Makewebbetter/subscriptions-for-woocommerce/files/7535645/subscriptions-for-woocommerce.txt)

QA issues:
[subscriptions-for-woocommerce QA issues.txt](https://github.com/Makewebbetter/subscriptions-for-woocommerce/files/7535634/subscriptions-for-woocommerce.QA.issues.txt)

**Comment by sumitshukla-cedcoss** [comment]
@ChiragGupta-CEDCOSS  fixable issues are fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.

**Comment by ChiragGupta-CEDCOSS** [comment]
Plugin: Subscriptions For WooCommerce
Version: 1.3.0

phpcs issues:
[subscriptions-for-woocommerce.txt](https://github.com/Makewebbetter/subscriptions-for-woocommerce/files/7815141/subscriptions-for-woocommerce.txt)

QA issues:
[subscriptions-for-woocommerce.QA.issues.txt](https://github.com/Makewebbetter/subscriptions-for-woocommerce/files/7815146/subscriptions-for-woocommerce.QA.issues.txt)

**Comment by mohammaddanish-cedcoss** [comment]
some phpcs issues are left and they can't be fixed.
because we did compatibility with WooEpay payment gateway and we are using this payment gateway object's properties which are not in the valid snake case format ( as per WordPress standard ).

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
