### ISSUE TITLE
Translation and Language issues.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/subscriptions-for-woocommerce#57]
Plugin name: Subscriptions For WooCommerce

**Translation issue:-**
- String: **MakeWebBetter** should not get translated.

**Grammatical issues:-**
#: admin/class-subscriptions-for-woocommerce-admin.php:287
msgid "Please submit a ticket , our team will respond within 24 hours."
msgstr ""
**--> "Please submit a ticket, our team will respond within 24 hours."**

#: admin/class-subscriptions-for-woocommerce-admin.php:357
msgid "This is the Subscriptions type product."
msgstr ""
**Subscriptions --> Subscription**

#: admin/partials/subscriptions-for-woocommerce-overview.php:76
msgid ""
"You can charge extra payment in the form of an initial fee. Stripe payment "
"integration of WooCommerce is supported with subscription."
msgstr ""
**subscription --> the subscription**

#: admin/partials/subscriptions-for-woocommerce-overview.php:100
msgid ""
"With a clean subscription report module, you will get complete subscription "
"data of all users.Find important details like active and inactive "
"subscriptions, next payment dates, product names, subscription expiry dates, "
"and due dates of the respective plans."
msgstr ""
**-->"With a clean subscription report module, you will get complete subscription "
"data of all users. Find important details like active and inactive "
"subscriptions, next payment dates, product names, subscription expiry dates, "
"and due dates of the respective plans."**

#: admin/partials/subscriptions-for-woocommerce-system-status.php:56
msgid "Sysytem Variables"
msgstr ""
**Sysytem --> System**

#: emails/class-subscriptions-for-woocommerce-cancel-subscription-email.php:37
msgid "This Email Notification Send if any susbcription is Cancelled"
msgstr ""
**susbcription --> subscription**

#: emails/class-subscriptions-for-woocommerce-expired-subscription-email.php:37
msgid "This Email Notification Send if any susbcription is Expired"
msgstr ""
**susbcription --> subscription**

#: package/gateways/stripe/class-subscriptions-for-woocommerce-stripe.php:57
msgid "Something Went Wrong. Please see log file for more info."
msgstr ""
**log --> the log**

#: public/class-subscriptions-for-woocommerce-public.php:734
msgid "Payment Method Added Sucessfully"
msgstr ""
**Sucessfully --> Successfully**

#: subscriptions-for-woocommerce.php:202
msgid "No Subscriptions found in trash"
msgstr ""
**trash --> the trash**

**Comment by ChiragGupta-CEDCOSS** [comment]
**Plugin: Subscriptions For WooCommerce
Version: 1.1.0**
**Translation issue:**
#: includes/subscriptions-for-woocommerce-common-function.php:652
#: public/class-subscriptions-for-woocommerce-public.php:125
#: public/class-subscriptions-for-woocommerce-public.php:139
#: public/class-subscriptions-for-woocommerce-public.php:961
#, php-format
msgid " / %s "

**Grammatical issues:**
#: includes/subscriptions-for-woocommerce-common-function.php:361
msgid "Invalid susbcription order."
--> Invalid subscription order.
#: subscriptions-for-woocommerce.php:256
msgid "This subscriptions are stored."
--> These subscriptions are stored.
#: public/class-subscriptions-for-woocommerce-public.php:1156
msgid "You can not add multiple subscription product in cart"
--> You can not add multiple subscription products in cart

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.

**Comment by ChiragGupta-CEDCOSS** [comment]
Plugin: Subscriptions For WooCommerce
Version: 1.2.0
Translation issue:
![Screenshot (32)](https://user-images.githubusercontent.com/76723329/141723510-204a5448-f89b-4f35-9972-2b90336e22b3.png)
![Screenshot (33)](https://user-images.githubusercontent.com/76723329/141723524-0b9c5984-a33a-4b04-814c-066be505755f.png)

**Comment by sumitshukla-cedcoss** [comment]
Fixable issues are fixed @ChiragGupta-CEDCOSS

**Comment by ChiragGupta-CEDCOSS** [comment]
#: build/index.js:56011
msgid ""
"Enter text to dispaly on \"Add to cart\" button for subscription products"
msgstr ""
--> "Enter text to display on \"Add to cart\" button for subscription products"

#: build/index.js:56024
msgid ""
"Enter text to dispaly on \"Place order\" button for subscription products"
msgstr ""
--> "Enter text to display on \"Place order\" button for subscription products"

#: package/gateways/woocybs/class-mwb-subscriptions-payment-woocybs-main.php:204
#, php-format
msgid ""
"Renewal Order is successfully payed!. Cardholder: %1$s Last 4 card digits: : "
"%2$s"
msgstr ""
--> "Renewal Order is successfully paid!. Cardholder: %1$s Last 4 card digits: : "

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine
