### ISSUE TITLE
Support page showing error message

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/subscriptions-for-woocommerce#76]
WordPress version: 5.7.2
WooCommerce version: 5.3.0
Area Path: Admin panel --> MakeWebBetter --> Subscriptions For WooCommerce --> Support
Version: 1.0.1
Description: The Support page is showing error message.
![Screenshot (14)](https://user-images.githubusercontent.com/76723329/118612702-aa6e2c80-b7db-11eb-885e-1fc5ca5cff7a.png)

**Comment by indresh-cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
