### ISSUE TITLE
Add Payment Method is not Working

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/subscriptions-for-woocommerce#77]
WordPress version: 5.7.2
WooCommerce version: 5.3.0
Area Path: Store-end --> My account --> Subscriptions
Version: 1.0.1
Description: Add Payment Method is not Working for Subscription having no signup fee and have free trial.
![Screenshot (15)](https://user-images.githubusercontent.com/76723329/118615463-6597c500-b7de-11eb-8b0d-97d0a825aebc.png)

![Screenshot (16)](https://user-images.githubusercontent.com/76723329/118615486-69c3e280-b7de-11eb-9707-a8336c69157d.png)

**Comment by indresh-cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
