### ISSUE TITLE
Subscriptions Per Interval field is not showing validation error with Subscriptions Expiry Interval field

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/subscriptions-for-woocommerce#78]
WordPress version: 5.7.2
WooCommerce version: 5.3.0
Area Path: Admin panel --> Products --> Subscriptions
Version: 1.0.1
Description: Subscriptions Per Interval field is not showing validation error with Subscriptions Expiry Interval field at values:
Subscriptions Per Interval- 10 or >10
Subscriptions Expiry Interval- any value less than the Subscriptions Per Interval interval value

Also check for values: (These values in correct format are showing error message and not accepting valid inputs)
Subscriptions Per Interval- 2 to 9
Subscriptions Expiry Interval- 10 to 29

![Screenshot (17)](https://user-images.githubusercontent.com/76723329/118654175-e918dc80-b805-11eb-85b7-3e8f52251014.png)

**Comment by indresh-cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
