### ISSUE TITLE
Subscription Settings tab is coming in all type of products

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/subscriptions-for-woocommerce#79]
WordPress version: 5.7.2
WooCommerce version: 5.3.0
Area Path: Admin panel --> Products --> Subscriptions
Version: 1.0.1
Description: **Subscription Settings** tab is coming in all type of products- Simple/ Grouped/ External/ Variable product.
Steps to be followed:
1. Simple product --> Subscription(check)
2. Go to Grouped/ External/ Variable product from drop-down and see 'Subscription Settings' tab.
3. Create subscription product of any type.
![Screenshot (22)](https://user-images.githubusercontent.com/76723329/118807827-66a42180-b8c6-11eb-9a2c-025037d6db46.png)
![Screenshot (23)](https://user-images.githubusercontent.com/76723329/118807905-7d4a7880-b8c6-11eb-8880-7225ea1d5ea9.png)
![Screenshot (24)](https://user-images.githubusercontent.com/76723329/118807955-8fc4b200-b8c6-11eb-9fa3-d8cf21a50e07.png)

**Comment by indresh-cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.

**Comment by ChiragGupta-CEDCOSS** [comment]
Now subscription Setting is coming without selecting the checkbox.
![Screenshot - 2021-06-10T182803 312](https://user-images.githubusercontent.com/76723329/121529009-9e137300-ca19-11eb-9dc5-5f3857c0f402.png)

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.

**Comment by ChiragGupta-CEDCOSS** [comment]
The issue coming again with **all types of products**.
![Screenshot (54)](https://user-images.githubusercontent.com/76723329/132619712-ef81fe2d-a561-483a-91d2-9e80e0ade0b2.png)

**Comment by indresh-cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
