### ISSUE TITLE
Subscriptions product description is visible with variable product.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/subscriptions-for-woocommerce#88]
WordPress version: 5.7.2
WooCommerce version: 5.3.0
Area Path: Admin panel --> Products --> Subscriptions
Version: 1.0.1
Description: Subscriptions product description is visible with the variable product while only org plugin is activated.
![Screenshot (15)](https://user-images.githubusercontent.com/76723329/120173537-bd442080-c221-11eb-9b12-a014cc13e21a.png)
![Screenshot (16)](https://user-images.githubusercontent.com/76723329/120173560-c1703e00-c221-11eb-9c17-37820148bd4b.png)

**Comment by indresh-cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
