### ISSUE TITLE
Settings saved message is pushing dashboard settings downwards.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/subscriptions-for-woocommerce#89]
WordPress version: 5.7.2
WooCommerce version: 5.3.0
Area Path: Admin panel --> MakeWebBetter --> Subscriptions For WooCommerce --> General Setting
Version: 1.0.1
Description: Settings saved message is pushing dashboard settings downwards.
![Screenshot (17)](https://user-images.githubusercontent.com/76723329/120174219-799de680-c222-11eb-818d-6765a37c89af.png)

**Comment by indresh-cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
