### ISSUE TITLE
Video is added two times in Overview.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/subscriptions-for-woocommerce#90]
WordPress version: 5.7.2
WooCommerce version: 5.3.0
Area Path: Admin panel --> MakeWebBetter --> Subscriptions For WooCommerce --> Overview
Version: 1.0.1
Description: Video is added two times in Overview it should be added only once.
![Screenshot (18)](https://user-images.githubusercontent.com/76723329/120175902-4e1bfb80-c224-11eb-8458-fdada6d41730.png)

**Comment by indresh-cedcoss** [comment]
Fix git issues

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
